-- Add comprehensive everyday African phrases (200+ total)
-- This script adds phrases to existing categories and introduces new ones

-- More Greetings (10 additional)
insert into public.phrases (category, english, english_pronunciation, english_context, shona, shona_pronunciation, shona_context, ndebele, ndebele_pronunciation, ndebele_context, chinese, chinese_pronunciation, chinese_context) values
('greetings', 'How''s your day going?', 'howz yor day GOH-ing', 'Casual check-in', 'Zuva rako rakadini?', 'ZOO-vah RAH-koh rah-kah-DEE-nee', 'Kubvunza nezuva', 'Unjani lamuhla?', 'oon-JAH-nee lah-MOO-hlah', 'Ukubuza ngosuku', '你今天怎么样?', 'nǐ jīn tiān zěn me yàng', '随意询问'),
('greetings', 'Long time no see', 'long time noh see', 'Haven''t met in while', 'Kwaita nguva', 'KWYE-tah nn-GOO-vah', 'Kusangana mushure menguva', 'Sekuyisikhathi', 'seh-koo-yee-see-KAH-thee', 'Ukubonana emva kwesikhathi', '好久不见', 'hǎo jiǔ bù jiàn', '很久没见'),
('greetings', 'Nice to meet you', 'nice too meet yoo', 'First meeting', 'Ndafara kukuziva', 'nn-dah-FAH-rah koo-koo-ZEE-vah', 'Kusangana kwekutanga', 'Ngiyajabula ukukwazi', 'ng-ee-yah-jah-BOO-lah oo-koo-KWAH-zee', 'Ukuhlangana kokuqala', '很高兴认识你', 'hěn gāo xìng rèn shi nǐ', '第一次见面'),
('greetings', 'How''s the family?', 'howz thuh FAM-i-lee', 'Asking about family', 'Mhuri yakadiniko?', 'mm-HOO-ree yah-kah-dee-NEE-koh', 'Kubvunza nezvemhuri', 'Umndeni unjani?', 'oom-nn-DEH-nee oon-JAH-nee', 'Ukubuza ngomndeni', '家人怎么样?', 'jiā rén zěn me yàng', '询问家人'),
('greetings', 'Give my regards', 'giv my ree-GARDZ', 'Send greetings', 'Ndikwazisirei', 'nn-dee-kwah-zee-SEE-ray', 'Kutumira kwaziso', 'Ngithinte', 'ng-ee-TEEN-teh', 'Ukuthumela imbingelelo', '代我问好', 'dài wǒ wèn hǎo', '转达问候'),
('greetings', 'What''s your name?', 'whats yor name', 'Asking for name', 'Munononzi?', 'moo-noh-NOHN-zee', 'Kubvunza zita', 'Ubani igama lakho?', 'oo-BAH-nee ee-GAH-mah LAH-koh', 'Ukubuza igama', '你叫什么名字?', 'nǐ jiào shén me míng zi', '询问姓名'),
('greetings', 'My name is...', 'my name iz', 'Introducing self', 'Ndinonzi...', 'nn-dee-NOHN-zee', 'Kuzvizivisa', 'Igama lami ngu...', 'ee-GAH-mah LAH-mee nn-goo', 'Ukuzazisa', '我叫...', 'wǒ jiào', '自我介绍'),
('greetings', 'Pleased to meet you', 'pleezd too meet yoo', 'Formal greeting', 'Ndakafara kukuziva', 'nn-dah-kah-FAH-rah koo-koo-ZEE-vah', 'Kwaziso yehuremekedzo', 'Ngijabulile ukukwazi', 'ng-ee-jah-boo-LEE-leh oo-koo-KWAH-zee', 'Ukubingelela ngokuhlonipha', '很荣幸认识你', 'hěn róng xìng rèn shi nǐ', '正式问候'),
('greetings', 'Have a nice day', 'hav uh nice day', 'Wishing well', 'Ite zuva rakanaka', 'EE-teh ZOO-vah rah-kah-NAH-kah', 'Kuda zvakanaka', 'Ube nosuku oluhle', 'oo-beh noh-SOO-koo oh-LOO-hleh', 'Ukufisela okuhle', '祝你今天愉快', 'zhù nǐ jīn tiān yú kuài', '祝福美好'),
('greetings', 'Take care', 'take kair', 'Showing concern', 'Chenjera', 'chehn-JEH-rah', 'Kuratidza hanya', 'Zinanzelele', 'zee-nahn-zeh-LEH-leh', 'Ukukhombisa ukunaka', '保重', 'bǎo zhòng', '表示关心');

-- Shopping & Market (25 phrases)
insert into public.phrases (category, english, english_pronunciation, english_context, shona, shona_pronunciation, shona_context, ndebele, ndebele_pronunciation, ndebele_context, chinese, chinese_pronunciation, chinese_context) values
('shopping', 'How much is this?', 'how much iz this', 'Asking price', 'Ichi chinodhura?', 'EE-chee chee-noh-DOO-rah', 'Kubvunza mutengo', 'Kuyimalini lokhu?', 'koo-yee-mah-LEE-nee LOH-koo', 'Ukubuza intengo', '这个多少钱?', 'zhè ge duō shao qián', '询问价格'),
('shopping', 'That''s too expensive', 'thats too ex-PEN-siv', 'Negotiating price', 'Zvinodhura zvikuru', 'zvee-noh-DOO-rah zvee-KOO-roo', 'Kukakavadzana mutengo', 'Kuyabiza', 'koo-yah-BEE-zah', 'Ukuxoxisana ngentengo', '太贵了', 'tài guì le', '讨价还价'),
('shopping', 'Can you reduce the price?', 'kan yoo ree-DOOS thuh price', 'Bargaining', 'Munogona kudzikisa here?', 'moo-noh-GOH-nah koo-dzee-KEE-sah HEH-reh', 'Kutsika mutengo', 'Unganciphisa yini?', 'oo-ngahn-chee-PEE-sah YEE-nee', 'Ukuncenga intengo', '能便宜一点吗?', 'néng pián yi yì diǎn ma', '讨价还价'),
('shopping', 'I''ll take it', 'ile take it', 'Accepting price', 'Ndichatora', 'nn-dee-chah-TOH-rah', 'Kubvuma mutengo', 'Ngizakuthatha', 'ng-ee-zah-koo-TAH-tah', 'Ukwamukela intengo', '我买了', 'wǒ mǎi le', '接受价格'),
('shopping', 'Do you have...?', 'doo yoo hav', 'Looking for item', 'Mune...?', 'MOO-neh', 'Kutsvaga chinhu', 'Unalo...?', 'oo-NAH-loh', 'Ukufuna into', '你有...吗?', 'nǐ yǒu... ma', '寻找物品'),
('shopping', 'I''m just looking', 'ime just LOOK-ing', 'Browsing', 'Ndiri kutarisa chete', 'nn-DEE-ree koo-tah-REE-sah CHEH-teh', 'Kungotarisa', 'Ngiyabuka nje', 'ng-ee-yah-BOO-kah nn-jeh', 'Ukubuka nje', '我只是看看', 'wǒ zhǐ shì kàn kan', '浏览'),
('shopping', 'Can I pay with card?', 'kan eye pay with kard', 'Payment method', 'Ndinogona kubhadhara nekadhi here?', 'nn-dee-noh-GOH-nah koo-bah-DAH-rah neh-KAH-dee HEH-reh', 'Nzira yekubhadhara', 'Ngingakhokhela ngekhadi yini?', 'ng-een-gah-koh-KEH-lah ng-eh-KAH-dee YEE-nee', 'Indlela yokukhokha', '可以刷卡吗?', 'kě yǐ shuā kǎ ma', '付款方式'),
('shopping', 'Cash only', 'kash OHN-lee', 'Payment restriction', 'Mari chete', 'MAH-ree CHEH-teh', 'Kushandisa mari chete', 'Imali kuphela', 'ee-MAH-lee koo-PEH-lah', 'Ukusebenzisa imali kuphela', '只收现金', 'zhǐ shōu xiàn jīn', '付款限制'),
('shopping', 'Can I get a receipt?', 'kan eye get uh ree-SEET', 'Requesting proof', 'Ndingawana risiti here?', 'nn-deen-gah-WAH-nah ree-SEE-tee HEH-reh', 'Kukumbira chitupa', 'Ngingathola irisidi yini?', 'ng-een-gah-TOH-lah ee-ree-SEE-dee YEE-nee', 'Ukucela ubufakazi', '能给我收据吗?', 'néng gěi wǒ shōu jù ma', '请求证明'),
('shopping', 'Is this fresh?', 'iz this fresh', 'Quality check', 'Ichi chinyowani here?', 'EE-chee chee-NYOH-wah-nee HEH-reh', 'Kutarisa mhando', 'Lokhu kusha yini?', 'LOH-koo KOO-shah YEE-nee', 'Ukuhlola ikhwalithi', '这个新鲜吗?', 'zhè ge xīn xiān ma', '质量检查'),
('shopping', 'I need a bag', 'eye need uh bag', 'Requesting carrier', 'Ndinoda bhegi', 'nn-dee-NOH-dah BEH-gee', 'Kukumbira bhegi', 'Ngidinga isikhwama', 'ng-ee-DEEN-gah ee-see-KWAH-mah', 'Ukucela isikhwama', '我需要袋子', 'wǒ xū yào dài zi', '请求袋子'),
('shopping', 'Where is the market?', 'wair iz thuh MAR-ket', 'Finding location', 'Musika uripiko?', 'moo-SEE-kah oo-ree-PEE-koh', 'Kutsvaga nzvimbo', 'Isitolo sikuphi?', 'ee-see-TOH-loh see-KOO-pee', 'Ukufuna indawo', '市场在哪里?', 'shì chǎng zài nǎ lǐ', '寻找位置'),
('shopping', 'What time does it close?', 'what time duz it klohz', 'Business hours', 'Inopfumbika nenguva yei?', 'ee-noh-PFOOM-bee-kah neh-nn-GOO-vah yay', 'Nguva yekuvhara', 'Kuvala ngasiphi isikhathi?', 'koo-VAH-lah ng-ah-SEE-pee ee-see-KAH-thee', 'Isikhathi sokuvala', '几点关门?', 'jǐ diǎn guān mén', '营业时间'),
('shopping', 'Can I try it on?', 'kan eye try it on', 'Fitting clothes', 'Ndingaedza here?', 'nn-deen-gah-EH-dzah HEH-reh', 'Kuedza kupfeka', 'Ngingakuzama yini?', 'ng-een-gah-koo-ZAH-mah YEE-nee', 'Ukuzama ukugqoka', '我可以试穿吗?', 'wǒ kě yǐ shì chuān ma', '试穿衣服'),
('shopping', 'This doesn''t fit', 'this DUZ-unt fit', 'Wrong size', 'Ichi hachinakire', 'EE-chee hah-chee-nah-KEE-reh', 'Saizi isiri iyo', 'Lokhu akulingani', 'LOH-koo ah-koo-leen-GAH-nee', 'Usayizi awufanele', '这个不合适', 'zhè ge bù hé shì', '尺寸不对'),
('shopping', 'Do you have a bigger size?', 'doo yoo hav uh BIG-ger size', 'Size request', 'Mune saizi hombe here?', 'MOO-neh SAI-zee HOHM-beh HEH-reh', 'Kukumbira saizi hombe', 'Unalo elikhulu yini?', 'oo-NAH-loh eh-lee-KOO-loo YEE-nee', 'Ukucela usayizi omkhulu', '有大一点的吗?', 'yǒu dà yì diǎn de ma', '请求尺寸'),
('shopping', 'Do you have a smaller size?', 'doo yoo hav uh SMAWL-er size', 'Size request', 'Mune saizi duku here?', 'MOO-neh SAI-zee DOO-koo HEH-reh', 'Kukumbira saizi duku', 'Unalo elincane yini?', 'oo-NAH-loh eh-leen-CAH-neh YEE-nee', 'Ukucela usayizi omncane', '有小一点的吗?', 'yǒu xiǎo yì diǎn de ma', '请求尺寸'),
('shopping', 'Can I return this?', 'kan eye ree-TURN this', 'Return policy', 'Ndinogona kudzosa here?', 'nn-dee-noh-GOH-nah koo-DZOH-sah HEH-reh', 'Mutemo wekudzosa', 'Ngingakubuyisela yini?', 'ng-een-gah-koo-boo-yee-SEH-lah YEE-nee', 'Umthetho wokubuyisela', '可以退货吗?', 'kě yǐ tuì huò ma', '退货政策'),
('shopping', 'Is there a warranty?', 'iz thair uh WAR-un-tee', 'Product guarantee', 'Pane waranti here?', 'PAH-neh wah-RAHN-tee HEH-reh', 'Chivimbiso chechigadzirwa', 'Kukhona iwaranti yini?', 'koo-KOH-nah ee-wah-RAHN-tee YEE-nee', 'Isiqinisekiso somkhiqizo', '有保修吗?', 'yǒu bǎo xiū ma', '产品保证'),
('shopping', 'I want to buy...', 'eye want too buy', 'Purchase intention', 'Ndoda kutenga...', 'nn-DOH-dah koo-TEHN-gah', 'Chinangwa chokutenga', 'Ngifuna ukuthenga...', 'ng-ee-FOO-nah oo-koo-TEHN-gah', 'Inhloso yokuthenga', '我想买...', 'wǒ xiǎng mǎi', '购买意向'),
('shopping', 'Keep the change', 'keep thuh chaynj', 'No change needed', 'Siyana nazvo', 'see-YAH-nah NAH-zvoh', 'Kusada shanduko', 'Gcinisipo', 'g-chee-NEE-see-poh', 'Awufuni ushintsho', '不用找了', 'bù yòng zhǎo le', '不需要找零'),
('shopping', 'Can you deliver?', 'kan yoo dee-LIV-er', 'Delivery service', 'Munogona kuunza here?', 'moo-noh-GOH-nah koo-OON-zah HEH-reh', 'Sevhisi yekuunza', 'Ungakuletha yini?', 'oo-ngah-koo-LEH-tah YEE-nee', 'Inkonzo yokuletha', '可以送货吗?', 'kě yǐ sòng huò ma', '配送服务'),
('shopping', 'How long will it take?', 'how long wil it take', 'Time estimate', 'Zvinotora nguva yakadini?', 'zvee-noh-TOH-rah nn-GOO-vah yah-kah-DEE-nee', 'Kufungidzira nguva', 'Kuzothatha isikhathi esingakanani?', 'koo-zoh-TAH-tah ee-see-KAH-thee eh-seen-gah-kah-NAH-nee', 'Ukulinganisa isikhathi', '要多久?', 'yào duō jiǔ', '时间估计'),
('shopping', 'Is this on sale?', 'iz this on sayl', 'Discount inquiry', 'Ichi chiri pamusika here?', 'EE-chee CHEE-ree pah-moo-SEE-kah HEH-reh', 'Kubvunza nezvemuzhinji', 'Lokhu kuyentengiso yini?', 'LOH-koo koo-yehn-tehn-GEE-soh YEE-nee', 'Ukubuza ngomkhankaso', '这个打折吗?', 'zhè ge dǎ zhé ma', '折扣查询'),
('shopping', 'Final price?', 'FY-nul price', 'Last offer', 'Mutengo wekupedzisira?', 'moo-TEHN-goh weh-koo-peh-dzee-SEE-rah', 'Chipo chekupedzisira', 'Intengo yokugcina?', 'een-TEHN-goh yoh-koo-g-CHEE-nah', 'Isinikelo sokugcina', '最后价格?', 'zuì hòu jià gé', '最终报价');

-- Food & Dining (25 phrases)
insert into public.phrases (category, english, english_pronunciation, english_context, shona, shona_pronunciation, shona_context, ndebele, ndebele_pronunciation, ndebele_context, chinese, chinese_pronunciation, chinese_context) values
('food', 'I''m hungry', 'ime HUN-gree', 'Need to eat', 'Ndine nzara', 'nn-DEE-neh nn-ZAH-rah', 'Kuda kudya', 'Ngilambile', 'ng-ee-lahm-BEE-leh', 'Ukufuna ukudla', '我饿了', 'wǒ è le', '需要吃饭'),
('food', 'I''m thirsty', 'ime THUR-stee', 'Need to drink', 'Ndine nyota', 'nn-DEE-neh NYOH-tah', 'Kuda kunwa', 'Ngomile', 'ng-oh-MEE-leh', 'Ukufuna ukuphuza', '我渴了', 'wǒ kě le', '需要喝水'),
('food', 'What do you recommend?', 'what doo yoo rek-uh-MEND', 'Menu advice', 'Munokuraireiwo?', 'moo-noh-koo-RYE-ray-woh', 'Zano pamusika', 'Ungicebisani?', 'oo-ng-ee-cheh-bee-SAH-nee', 'Iseluleko ngemenyu', '你推荐什么?', 'nǐ tuī jiàn shén me', '菜单建议'),
('food', 'This is delicious', 'this iz dee-LISH-us', 'Compliment food', 'Ichi chinotapira', 'EE-chee chee-noh-tah-PEE-rah', 'Kurumbidza chikafu', 'Lokhu kuyamnandi', 'LOH-koo koo-yahm-NAHN-dee', 'Ukubonga ukudla', '这个很好吃', 'zhè ge hěn hǎo chī', '称赞食物'),
('food', 'Can I have the menu?', 'kan eye hav thuh MEN-yoo', 'Request menu', 'Ndingawana menyu here?', 'nn-deen-gah-WAH-nah MEH-nyoo HEH-reh', 'Kukumbira menyu', 'Ngingathola imenyu yini?', 'ng-een-gah-TOH-lah ee-MEH-nyoo YEE-nee', 'Ukucela imenyu', '能给我菜单吗?', 'néng gěi wǒ cài dān ma', '请求菜单'),
('food', 'I''d like to order', 'ide like too OR-der', 'Ready to order', 'Ndinoda kuodha', 'nn-dee-NOH-dah koo-OH-dah', 'Kugadzirira kuodha', 'Ngifuna uku-oda', 'ng-ee-FOO-nah oo-koo-OH-dah', 'Ukulungela uku-oda', '我想点餐', 'wǒ xiǎng diǎn cān', '准备点餐'),
('food', 'No meat please', 'noh meet pleez', 'Dietary restriction', 'Pasina nyama ndapota', 'pah-SEE-nah NYAH-mah nn-dah-POH-tah', 'Zvisungo zvekudya', 'Kungenaminyama ngicela', 'koo-ng-eh-nah-mee-NYAH-mah ng-ee-SEH-lah', 'Imikhawulo yokudla', '不要肉,谢谢', 'bù yào ròu xiè xie', '饮食限制'),
('food', 'Is it spicy?', 'iz it SPY-see', 'Spice level', 'Inopisa here?', 'ee-noh-PEE-sah HEH-reh', 'Mwero wekupisa', 'Kuyashisa yini?', 'koo-yah-SHEE-sah YEE-nee', 'Izinga lokushisa', '辣吗?', 'là ma', '辣度'),
('food', 'Not too spicy', 'not too SPY-see', 'Preference', 'Musapisa zvikuru', 'moo-sah-PEE-sah zvee-KOO-roo', 'Zvakanaka', 'Ningashisi kakhulu', 'neen-gah-SHEE-see kah-KOO-loo', 'Okuhle', '不要太辣', 'bù yào tài là', '偏好'),
('food', 'Can I have water?', 'kan eye hav WAW-ter', 'Drink request', 'Ndingawana mvura here?', 'nn-deen-gah-WAH-nah mm-VOO-rah HEH-reh', 'Kukumbira mvura', 'Ngingathola amanzi yini?', 'ng-een-gah-TOH-lah ah-MAHN-zee YEE-nee', 'Ukucela amanzi', '能给我水吗?', 'néng gěi wǒ shuǐ ma', '饮料请求'),
('food', 'The check please', 'thuh chek pleez', 'Request bill', 'Bhiri ndapota', 'BEE-ree nn-dah-POH-tah', 'Kukumbira bhiri', 'Ibhili ngicela', 'ee-BEE-lee ng-ee-SEH-lah', 'Ukucela ibhili', '买单,谢谢', 'mǎi dān xiè xie', '请求账单'),
('food', 'Where''s the bathroom?', 'wairz thuh BATH-room', 'Facilities', 'Chimbuzi chiriko?', 'cheem-BOO-zee CHEE-ree-koh', 'Nzvimbo dzekushandisa', 'Indlu yangasese ikuphi?', 'een-DLOO yah-ngah-SEH-seh ee-KOO-pee', 'Izindawo zokugeza', '洗手间在哪里?', 'xǐ shǒu jiān zài nǎ lǐ', '设施'),
('food', 'Can we sit outside?', 'kan wee sit OWT-side', 'Seating preference', 'Tingagara kunze here?', 'teen-gah-GAH-rah KOON-zeh HEH-reh', 'Kuda kugara kunze', 'Singahlala ngaphandle yini?', 'seen-gah-HLAH-lah ng-ah-PHAHN-dleh YEE-nee', 'Ukuthanda ukukhala ngaphandle', '我们可以坐外面吗?', 'wǒ men kě yǐ zuò wài miàn ma', '座位偏好'),
('food', 'Do you have WiFi?', 'doo yoo hav WY-fy', 'Internet access', 'Mune WiFi here?', 'MOO-neh WY-fy HEH-reh', 'Kubatana neinternet', 'Unalo i-WiFi yini?', 'oo-NAH-loh ee-WY-fy YEE-nee', 'Ukuxhuma ku-intanethi', '有WiFi吗?', 'yǒu WiFi ma', '互联网接入'),
('food', 'This is cold', 'this iz kohld', 'Food temperature', 'Ichi chinotonhora', 'EE-chee chee-noh-tohn-HOH-rah', 'Tembiricha yechikafu', 'Lokhu kuyabanda', 'LOH-koo koo-yah-BAHN-dah', 'Izinga lokushisa kokudla', '这个凉了', 'zhè ge liáng le', '食物温度'),
('food', 'Can you heat it up?', 'kan yoo heet it up', 'Temperature request', 'Mungachidziyisa here?', 'moon-gah-chee-dzee-YEE-sah HEH-reh', 'Kukumbira kudziya', 'Lingakufudumeza yini?', 'lee-ngah-koo-foo-doo-MEH-zah YEE-nee', 'Ukucela ukufudumeza', '能加热吗?', 'néng jiā rè ma', '温度请求'),
('food', 'No sugar please', 'noh SHUG-er pleez', 'Diet preference', 'Pasina shuga ndapota', 'pah-SEE-nah SHOO-gah nn-dah-POH-tah', 'Kuda kudya', 'Kungelashukela ngicela', 'koo-ng-eh-lah-shoo-KEH-lah ng-ee-SEH-lah', 'Ukuthanda ukudla', '不要糖,谢谢', 'bù yào táng xiè xie', '饮食偏好'),
('food', 'Do you have tea?', 'doo yoo hav tee', 'Beverage inquiry', 'Mune tii here?', 'MOO-neh tee HEH-reh', 'Kubvunza nezvinwiwa', 'Unalo itiye yini?', 'oo-NAH-loh ee-TEE-yeh YEE-nee', 'Ukubuza ngephuzo', '有茶吗?', 'yǒu chá ma', '饮料询问'),
('food', 'With milk', 'with milk', 'Beverage preference', 'Nemukaka', 'neh-moo-KAH-kah', 'Kuda mukaka', 'Ngobisi', 'ng-oh-BEE-see', 'Ukufuna ubisi', '加牛奶', 'jiā niú nǎi', '饮料偏好'),
('food', 'Without milk', 'with-OWT milk', 'Beverage preference', 'Pasina mukaka', 'pah-SEE-nah moo-KAH-kah', 'Kusada mukaka', 'Kungelobisi', 'koo-ng-eh-loh-BEE-see', 'Ukungafuni ubisi', '不加牛奶', 'bù jiā niú nǎi', '饮料偏好'),
('food', 'This is enough', 'this iz ee-NUF', 'Satisfaction', 'Izvi zvakaringana', 'EE-zvee zvah-kah-reen-GAH-nah', 'Kugutsikana', 'Lokhu kwanele', 'LOH-koo KWAH-neh-leh', 'Ukaneliseka', '够了', 'gòu le', '满意'),
('food', 'Can I take this home?', 'kan eye take this hohm', 'Takeaway request', 'Ndingaenda nazvo kumba here?', 'nn-deen-gah-EHN-dah NAH-zvoh KOOM-bah HEH-reh', 'Kukumbira kutakura', 'Ngingakuhamba lakho ekhaya yini?', 'ng-een-gah-koo-HAM-bah LAH-koh eh-KAH-yah YEE-nee', 'Ukucela ukuhamba nakho', '可以打包吗?', 'kě yǐ dǎ bāo ma', '打包请求'),
('food', 'Do you deliver?', 'doo yoo dee-LIV-er', 'Delivery service', 'Munounza here?', 'moo-noh-OON-zah HEH-reh', 'Sevhisi yekuunza', 'Uyaletha yini?', 'oo-yah-LEH-tah YEE-nee', 'Inkonzo yokuletha', '你们送外卖吗?', 'nǐ men sòng wài mài ma', '外卖服务'),
('food', 'I have allergies', 'eye hav AL-er-jeez', 'Health concern', 'Ndine allergies', 'nn-DEE-neh ah-LER-jeez', 'Zvinhu zvinondikuvadza', 'Nginezimpilo', 'ng-ee-neh-zeem-PEE-loh', 'Izinkinga zempilo', '我有过敏', 'wǒ yǒu guò mǐn', '健康问题'),
('food', 'What''s in this dish?', 'whats in this dish', 'Ingredient inquiry', 'Pane chii muchikafu ichi?', 'PAH-neh chee moo-chee-KAH-foo EE-chee', 'Kubvunza zvinhu', 'Yini kulokhu kudla?', 'YEE-nee koo-LOH-koo KOO-dlah', 'Ukubuza ngezithako', '这道菜里有什么?', 'zhè dào cài lǐ yǒu shén me', '食材询问');

-- Health & Emergency (20 phrases)
insert into public.phrases (category, english, english_pronunciation, english_context, shona, shona_pronunciation, shona_context, ndebele, ndebele_pronunciation, ndebele_context, chinese, chinese_pronunciation, chinese_context) values
('health', 'I need a doctor', 'eye need uh DOK-ter', 'Medical emergency', 'Ndinoda chiremba', 'nn-dee-NOH-dah chee-REHM-bah', 'Dambudziko rekurapa', 'Ngidinga udokotela', 'ng-ee-DEEN-gah oo-doh-koh-TEH-lah', 'Isimo esiphuthumayo sezempilo', '我需要医生', 'wǒ xū yào yī shēng', '医疗紧急情况'),
('health', 'Call an ambulance', 'kawl an AM-byu-lans', 'Emergency response', 'Sheedzai ambulenzi', 'SHEH-dzye ahm-boo-LEHN-zee', 'Mhinduro yedambudziko', 'Fonela i-ambulensi', 'foh-NEH-lah ee-ahm-boo-LEHN-see', 'Ukuphendula kwesimo esiphuthumayo', '叫救护车', 'jiào jiù hù chē', '紧急响应'),
('health', 'I''m sick', 'ime sik', 'Feeling unwell', 'Ndiri kurwara', 'nn-DEE-ree koo-RWAH-rah', 'Kunzwa zvisina kunaka', 'Ngiyagula', 'ng-ee-yah-GOO-lah', 'Ukuzizwa ungaphilile', '我生病了', 'wǒ shēng bìng le', '感觉不舒服'),
('health', 'Where''s the hospital?', 'wairz thuh HOS-pi-tul', 'Finding healthcare', 'Chipatara chiriko?', 'chee-pah-TAH-rah CHEE-ree-koh', 'Kutsvaga nzvimbo yekurapa', 'Isibhedlela sikuphi?', 'ee-see-beh-DLEH-lah see-KOO-pee', 'Ukufuna indawo yokwelapha', '医院在哪里?', 'yī yuàn zài nǎ lǐ', '寻找医疗服务'),
('health', 'I have a headache', 'eye hav uh HED-ayk', 'Common ailment', 'Musoro wangu unorwadza', 'moo-SOH-roh WAH-ngoo oo-noh-RWAH-dzah', 'Chirwere chinowanikwa', 'Ikhanda lami liyabuhlungu', 'ee-KAHN-dah LAH-mee lee-yah-boo-HLOON-goo', 'Ukugula okuvamile', '我头痛', 'wǒ tóu tòng', '常见疾病'),
('health', 'I have a fever', 'eye hav uh FEE-ver', 'High temperature', 'Ndine fivha', 'nn-DEE-neh FEE-vah', 'Tembiricha yakakwira', 'Nginomkhuhlane', 'ng-ee-noh-m-koo-HLAH-neh', 'Izinga lokushisa eliphezulu', '我发烧了', 'wǒ fā shāo le', '高温'),
('health', 'I need medicine', 'eye need MED-i-sin', 'Treatment request', 'Ndinoda mushonga', 'nn-dee-NOH-dah moo-SHOHN-gah', 'Kukumbira kurapwa', 'Ngidinga umuthi', 'ng-ee-DEEN-gah oo-MOO-tee', 'Ukucela ukwelashwa', '我需要药', 'wǒ xū yào yào', '治疗请求'),
('health', 'Where''s the pharmacy?', 'wairz thuh FAR-muh-see', 'Finding medication', 'Pharmacy iriko?', 'FAR-muh-see EE-ree-koh', 'Kutsvaga mushonga', 'Ikhemisi likuphi?', 'ee-keh-MEE-see lee-KOO-pee', 'Ukufuna imithi', '药店在哪里?', 'yào diàn zài nǎ lǐ', '寻找药品'),
('health', 'I''m allergic to...', 'ime uh-LUR-jik too', 'Medical condition', 'Ndinoshungurudzwa ne...', 'nn-dee-noh-shoon-goo-ROO-dzwah neh', 'Mamiriro emuviri', 'Nginezimpilo ku...', 'ng-ee-neh-zeem-PEE-loh koo', 'Isimo sempilo', '我对...过敏', 'wǒ duì... guò mǐn', '医疗状况'),
('health', 'It hurts here', 'it hurts heer', 'Pain location', 'Kunorwadza pano', 'koo-noh-RWAH-dzah PAH-noh', 'Nzvimbo yekurwadziwa', 'Kubuhlungu lapha', 'koo-boo-HLOON-goo LAH-phah', 'Indawo yobuhlungu', '这里痛', 'zhè lǐ tòng', '疼痛位置'),
('health', 'Help!', 'help', 'Emergency call', 'Ndibatsirei!', 'nn-dee-bah-TSEE-ray', 'Kuchema rubatsiro', 'Ngisizeni!', 'ng-ee-SEE-zeh-nee', 'Ukumemeza usizo', '救命!', 'jiù mìng', '紧急呼叫'),
('health', 'I need help', 'eye need help', 'Requesting assistance', 'Ndinoda rubatsiro', 'nn-dee-NOH-dah roo-bah-TSEE-roh', 'Kukumbira rubatsiro', 'Ngidinga usizo', 'ng-ee-DEEN-gah oo-SEE-zoh', 'Ukucela usizo', '我需要帮助', 'wǒ xū yào bāng zhù', '请求帮助'),
('health', 'Fire!', 'fy-er', 'Emergency alert', 'Moto!', 'MOH-toh', 'Chengetedzo yedambudziko', 'Umlilo!', 'oom-LEE-loh', 'Isexwayiso esiphuthumayo', '着火了!', 'zháo huǒ le', '紧急警报'),
('health', 'Police!', 'puh-LEES', 'Emergency service', 'Mapurisa!', 'mah-poo-REE-sah', 'Sevhisi yedambudziko', 'Amaphoyisa!', 'ah-mah-phoh-YEE-sah', 'Inkonzo ephuthumayo', '警察!', 'jǐng chá', '紧急服务'),
('health', 'I''m lost', 'ime lawst', 'Need directions', 'Ndarasika', 'nn-dah-rah-SEE-kah', 'Kuda nzira', 'Ngilahlekile', 'ng-ee-lah-hleh-KEE-leh', 'Ukufuna izikhombisi', '我迷路了', 'wǒ mí lù le', '需要指引'),
('health', 'Can you help me?', 'kan yoo help mee', 'Request assistance', 'Mungandibatsira here?', 'moon-gahn-dee-bah-TSEE-rah HEH-reh', 'Kukumbira rubatsiro', 'Lingangisiza yini?', 'lee-ngahn-gee-SEE-zah YEE-nee', 'Ukucela usizo', '你能帮我吗?', 'nǐ néng bāng wǒ ma', '请求协助'),
('health', 'I feel dizzy', 'eye feel DIZ-ee', 'Health symptom', 'Ndinonzwa musoro uchitenderera', 'nn-dee-NOHN-zwah moo-SOH-roh oo-chee-tehn-deh-REH-rah', 'Chiratidzo cheutano', 'Ngizwa ngihhahamazekile', 'ng-eez-wah ng-ee-hah-hah-mah-zeh-KEE-leh', 'Uphawu lwempilo', '我头晕', 'wǒ tóu yūn', '健康症状'),
('health', 'I can''t breathe', 'eye kant breeth', 'Serious symptom', 'Handikwanisi kufema', 'hahn-dee-KWAH-nee-see koo-FEH-mah', 'Chiratidzo chakaoma', 'Angikwazi ukuphefumula', 'ah-ng-ee-KWAH-zee oo-koo-pheh-foo-MOO-lah', 'Uphawu olunzima', '我无法呼吸', 'wǒ wú fǎ hū xī', '严重症状'),
('health', 'Where''s my family?', 'wairz my FAM-i-lee', 'Emergency concern', 'Mhuri yangu iripi?', 'mm-HOO-ree YAH-ngoo ee-REE-pee', 'Hanya yedambudziko', 'Umndeni wami ukuphi?', 'oom-nn-DEH-nee WAH-mee oo-KOO-pee', 'Ukukhathazeka okophuthumayo', '我的家人在哪里?', 'wǒ de jiā rén zài nǎ lǐ', '紧急关注'),
('health', 'I need water', 'eye need WAW-ter', 'Basic need', 'Ndinoda mvura', 'nn-dee-NOH-dah mm-VOO-rah', 'Chinhu chinokosha', 'Ngidinga amanzi', 'ng-ee-DEEN-gah ah-MAHN-zee', 'Isidingo esiyisisekelo', '我需要水', 'wǒ xū yào shuǐ', '基本需求');

-- Transportation (20 phrases)
insert into public.phrases (category, english, english_pronunciation, english_context, shona, shona_pronunciation, shona_context, ndebele, ndebele_pronunciation, ndebele_context, chinese, chinese_pronunciation, chinese_context) values
('transport', 'Where''s the taxi?', 'wairz thuh TAK-see', 'Finding transport', 'Taxi iripi?', 'TAK-see ee-REE-pee', 'Kutsvaga mafambiro', 'Itheksi likuphi?', 'ee-TEHK-see lee-KOO-pee', 'Ukufuna ezokuthutha', '出租车在哪里?', 'chū zū chē zài nǎ lǐ', '寻找交通'),
('transport', 'How much to...?', 'how much too', 'Price inquiry', 'Kusvika ku... kunodhura?', 'koo-SVEE-kah koo koo-noh-DOO-rah', 'Kubvunza mutengo', 'Ukuya ku... kuyimalini?', 'oo-KOO-yah koo koo-yee-mah-LEE-nee', 'Ukubuza intengo', '到...多少钱?', 'dào... duō shao qián', '价格询问'),
('transport', 'Take me to...', 'take mee too', 'Destination request', 'Ndisvitse ku...', 'nn-dee-SVEE-tseh koo', 'Kukumbira kuendeswa', 'Ngiyise ku...', 'ng-ee-YEE-seh koo', 'Ukucela ukuyiswa', '带我去...', 'dài wǒ qù', '目的地请求'),
('transport', 'Stop here', 'stop heer', 'Driver instruction', 'Mira pano', 'MEE-rah PAH-noh', 'Kuraira mutyairi', 'Misa lapha', 'MEE-sah LAH-phah', 'Umyalelo womshayeli', '在这里停', 'zài zhè lǐ tíng', '司机指示'),
('transport', 'Wait for me', 'wayt for mee', 'Request to stay', 'Ndimirire', 'nn-dee-mee-REE-reh', 'Kukumbira kumirira', 'Ngilindele', 'ng-ee-leen-DEH-leh', 'Ukucela ukulinda', '等我', 'děng wǒ', '请求等待'),
('transport', 'I''m in a hurry', 'ime in uh HUR-ee', 'Time pressure', 'Ndiri pakukurumidza', 'nn-DEE-ree pah-koo-koo-roo-MEE-dzah', 'Kumanikidza nguva', 'Ngiyashesha', 'ng-ee-yah-SHEH-shah', 'Ukucindezelwa yisikhathi', '我很赶时间', 'wǒ hěn gǎn shí jiān', '时间压力'),
('transport', 'Which bus goes to...?', 'which bus gohz too', 'Route inquiry', 'Bhazi ripi rinoenda ku...?', 'BAH-zee REE-pee ree-noh-EHN-dah koo', 'Kubvunza nzira', 'Ibhasi liphi eliya ku...?', 'ee-BAH-see LEE-pee eh-lee-YAH koo', 'Ukubuza ngemizila', '哪辆公交车去...?', 'nǎ liàng gōng jiāo chē qù', '路线询问'),
('transport', 'When does it leave?', 'when duz it leev', 'Departure time', 'Rinobva rini?', 'ree-noh-BVAH REE-nee', 'Nguva yekubva', 'Lisuka nini?', 'lee-SOO-kah NEE-nee', 'Isikhathi sokusuka', '什么时候出发?', 'shén me shí hou chū fā', '出发时间'),
('transport', 'How long is the journey?', 'how long iz thuh JUR-nee', 'Travel duration', 'Rwendo rwacho rwakadini?', 'RWEHN-doh RWAH-choh rwah-kah-DEE-nee', 'Nguva yerwendo', 'Uhambo luthatha isikhathi esingakanani?', 'oo-HAHM-boh loo-TAH-tah ee-see-KAH-thee eh-seen-gah-kah-NAH-nee', 'Isikhathi sohambo', '旅程多长时间?', 'lǚ chéng duō cháng shí jiān', '旅行时长'),
('transport', 'One ticket please', 'wun TIK-it pleez', 'Ticket purchase', 'Tikiti imwe ndapota', 'tee-KEE-tee EEM-weh nn-dah-POH-tah', 'Kutenga tikiti', 'Ithikithi elilodwa ngicela', 'ee-tee-KEE-tee eh-lee-LOH-dwah ng-ee-SEH-lah', 'Ukuthenga ithikithi', '一张票,谢谢', 'yī zhāng piào xiè xie', '购票'),
('transport', 'Round trip', 'rownd trip', 'Return journey', 'Rwendo rwekunodzoka', 'RWEHN-doh RWEH-koo-noh-DZOH-kah', 'Rwendo rwekudzoka', 'Uhambo lokubuyela', 'oo-HAHM-boh loh-koo-boo-YEH-lah', 'Uhambo lokubuyela', '往返票', 'wǎng fǎn piào', '返程旅行'),
('transport', 'Is this seat taken?', 'iz this seet TAY-ken', 'Seating inquiry', 'Chigaro ichi chatora here?', 'chee-GAH-roh EE-chee chah-TOH-rah HEH-reh', 'Kubvunza nezvechigaro', 'Lesi sihlalo sithathiwe yini?', 'LEH-see see-HLAH-loh see-tah-TEE-weh YEE-nee', 'Ukubuza ngesihlalo', '这个座位有人吗?', 'zhè ge zuò wèi yǒu rén ma', '座位询问'),
('transport', 'Can you go faster?', 'kan yoo goh FAS-ter', 'Speed request', 'Mungakurumidza here?', 'moon-gah-koo-roo-MEE-dzah HEH-reh', 'Kukumbira kumhanya', 'Lingashesha yini?', 'lee-ngah-SHEH-shah YEE-nee', 'Ukucela ukushesha', '能开快点吗?', 'néng kāi kuài diǎn ma', '速度请求'),
('transport', 'Can you go slower?', 'kan yoo goh SLOH-er', 'Speed concern', 'Mungadzikisa kumhanya here?', 'moon-gah-dzee-KEE-sah koo-MHAH-nyah HEH-reh', 'Kukumbira kunononoka', 'Linganciphise ijubane yini?', 'lee-ngahn-chee-PEE-seh ee-joo-BAH-neh YEE-nee', 'Ukucela ukunciphisa ijubane', '能开慢点吗?', 'néng kāi màn diǎn ma', '速度担忧'),
('transport', 'I''ll walk', 'ile wawk', 'Transportation choice', 'Ndichafamba netsoka', 'nn-dee-chah-FAHM-bah neh-TSOH-kah', 'Kusarudza mafambiro', 'Ngizohamba ngenyawo', 'ng-ee-zoh-HAHM-bah ng-eh-NYAH-woh', 'Ukukhetha ezokuthutha', '我走路', 'wǒ zǒu lù', '交通选择'),
('transport', 'Where''s the train station?', 'wairz thuh trayn STAY-shun', 'Finding location', 'Chiteshi chebhazi repamutsetse chiriko?', 'chee-TEH-shee cheh-BAH-zee reh-pah-moo-TSEH-tseh CHEE-ree-koh', 'Kutsvaga nzvimbo', 'Isiteshi esithutha sikuphi?', 'ee-see-TEH-shee eh-see-TOO-tah see-KOO-pee', 'Ukufuna indawo', '火车站在哪里?', 'huǒ chē zhàn zài nǎ lǐ', '寻找位置'),
('transport', 'Can I rent a car?', 'kan eye rent uh kar', 'Vehicle rental', 'Ndingahaya motokari here?', 'nn-deen-gah-HAH-yah moh-toh-KAH-ree HEH-reh', 'Kuhaya motokari', 'Ngingaqasha imota yini?', 'ng-een-gah-QAH-shah ee-MOH-tah YEE-nee', 'Ukuqasha imoto', '我能租车吗?', 'wǒ néng zū chē ma', '车辆租赁'),
('transport', 'Fill it up', 'fil it up', 'Fuel request', 'Zadza peturu', 'ZAH-dzah peh-TOO-roo', 'Kukumbira peturu', 'Gcwalisa uphethiloli', 'g-CHWAH-lee-sah oo-peh-tee-LOH-lee', 'Ukucela uphethilohi', '加满油', 'jiā mǎn yóu', '加油请求'),
('transport', 'Check the tires', 'chek thuh ty-erz', 'Vehicle maintenance', 'Tarisa matairi', 'tah-REE-sah mah-TYE-ree', 'Kugadzirisa motokari', 'Hlola amatayela', 'HLOH-lah ah-mah-tah-YEH-lah', 'Ukulungisa imoto', '检查轮胎', 'jiǎn chá lún tāi', '车辆维护'),
('transport', 'The car broke down', 'thuh kar brohk down', 'Vehicle problem', 'Motokari yaparadza', 'moh-toh-KAH-ree yah-pah-RAH-dzah', 'Dambudziko remotokari', 'Imota yonakele', 'ee-MOH-tah yoh-nah-KEH-leh', 'Inkinga yemoto', '车坏了', 'chē huài le', '车辆问题');

-- School & Education (15 phrases)
insert into public.phrases (category, english, english_pronunciation, english_context, shona, shona_pronunciation, shona_context, ndebele, ndebele_pronunciation, ndebele_context, chinese, chinese_pronunciation, chinese_context) values
('school', 'Where is the school?', 'wair iz thuh skool', 'Finding location', 'Chikoro chiriko?', 'chee-KOH-roh CHEE-ree-koh', 'Kutsvaga nzvimbo', 'Isikole sikuphi?', 'ee-see-KOH-leh see-KOO-pee', 'Ukufuna indawo', '学校在哪里?', 'xué xiào zài nǎ lǐ', '寻找位置'),
('school', 'I am a student', 'eye am uh STOO-dent', 'Identity', 'Ndiri mudzidzi', 'nn-DEE-ree moo-DZEE-dzee', 'Kuzivisa', 'Ngingumfundi', 'ng-een-goo-m-FOON-dee', 'Ukuzazisa', '我是学生', 'wǒ shì xué shēng', '身份'),
('school', 'I am a teacher', 'eye am uh TEE-cher', 'Profession', 'Ndiri mudzidzisi', 'nn-DEE-ree moo-dzee-DZEE-see', 'Basa', 'Ngingumfundisi', 'ng-een-goo-m-foon-DEE-see', 'Umsebenzi', '我是老师', 'wǒ shì lǎo shī', '职业'),
('school', 'Can I borrow a pen?', 'kan eye BAR-oh uh pen', 'Request', 'Ndingakwereta peni here?', 'nn-deen-gah-KWEH-reh-tah PEH-nee HEH-reh', 'Kukumbira', 'Ngingaboleka usiba yini?', 'ng-een-gah-boh-LEH-kah oo-SEE-bah YEE-nee', 'Ukucela', '能借我一支笔吗?', 'néng jiè wǒ yī zhī bǐ ma', '请求'),
('school', 'What''s the homework?', 'whats thuh HOHM-wurk', 'Assignment inquiry', 'Basa repamba nderei?', 'BAH-sah reh-PAHM-bah nn-DEH-ray', 'Kubvunza nezano', 'Umsebenzi wasekhaya uyini?', 'oom-seh-BEHN-zee wah-seh-KAH-yah oo-YEE-nee', 'Ukubuza ngomsebenzi', '作业是什么?', 'zuò yè shì shén me', '作业询问'),
('school', 'When is the exam?', 'when iz thee ex-AM', 'Test schedule', 'Bvunzo richaitika rini?', 'BVOON-zoh ree-chai-TEE-kah REE-nee', 'Purogiramu yebvunzo', 'Isivivinyo sizakuba nini?', 'ee-see-vee-VEE-nyoh see-zah-KOO-bah NEE-nee', 'Isheduli yokuhlolwa', '考试什么时候?', 'kǎo shì shén me shí hou', '考试时间'),
('school', 'I don''t understand', 'eye dohnt un-der-STAND', 'Comprehension issue', 'Handisi kunzwisisa', 'hahn-DEE-see koo-nn-zwee-SEE-sah', 'Dambudziko rekunzwisisa', 'Angiqondi', 'ah-ng-ee-QOHN-dee', 'Inkinga yokuqonda', '我不明白', 'wǒ bù míng bai', '理解问题'),
('school', 'Can you explain?', 'kan yoo ex-PLAYN', 'Request clarification', 'Mungatsanangure here?', 'moon-gah-tsah-nahn-GOO-reh HEH-reh', 'Kukumbira tsananguro', 'Lingachaza yini?', 'lee-ngah-CHAH-zah YEE-nee', 'Ukucela incazelo', '能解释一下吗?', 'néng jiě shì yí xià ma', '请求解释'),
('school', 'Can you repeat that?', 'kan yoo ree-PEET that', 'Repetition request', 'Mungadzokorora here?', 'moon-gah-dzoh-koh-ROH-rah HEH-reh', 'Kukumbira kudzokorora', 'Lingakuphinda yini?', 'lee-ngah-koo-PHEEN-dah YEE-nee', 'Ukucela ukuphinda', '能重复一遍吗?', 'néng chóng fù yí biàn ma', '重复请求'),
('school', 'What page are we on?', 'what payj ar wee on', 'Following along', 'Tiri paperji ripi?', 'TEE-ree pah-PEH-jee REE-pee', 'Kutevera', 'Sikuyo iphi ikhasi?', 'see-KOO-yoh EE-pee ee-KAH-see', 'Ukulandela', '我们在第几页?', 'wǒ men zài dì jǐ yè', '跟随'),
('school', 'May I be excused?', 'may eye bee ex-KYOOZD', 'Permission to leave', 'Ndingabude here?', 'nn-deen-gah-BOO-deh HEH-reh', 'Kukumbira mvumo', 'Ngingaphuma yini?', 'ng-een-gah-PHOO-mah YEE-nee', 'Ukucela imvume yokuphuma', '我可以离开吗?', 'wǒ kě yǐ lí kāi ma', '请求离开'),
('school', 'I have a question', 'eye hav uh KWEST-yun', 'Inquiry', 'Ndine mubvunzo', 'nn-DEE-neh moo-BVOON-zoh', 'Kubvunza', 'Nginombuzo', 'ng-ee-nohm-BOO-zoh', 'Ukubuza', '我有一个问题', 'wǒ yǒu yí ge wèn tí', '询问'),
('school', 'Good job!', 'good job', 'Encouragement', 'Waita mushe!', 'WAI-tah MOO-sheh', 'Kukurudzira', 'Wenze kahle!', 'WEHN-zeh KAH-leh', 'Ukukhuthaza', '做得好!', 'zuò de hǎo', '鼓励'),
('school', 'Study hard', 'STUD-ee hard', 'Advice', 'Udzidze nesimba', 'oo-DZEE-dzeh neh-SEEM-bah', 'Zano', 'Funda kanzima', 'FOON-dah kahn-ZEE-mah', 'Iseluleko', '努力学习', 'nǔ lì xué xí', '建议'),
('school', 'Break time', 'brayk time', 'Rest period', 'Nguva yekuzorora', 'nn-GOO-vah yeh-koo-zoh-ROH-rah', 'Nguva yekupumzika', 'Isikhathi sokuphumula', 'ee-see-KAH-thee soh-koo-phoo-MOO-lah', 'Isikhathi sokuphumula', '休息时间', 'xiū xi shí jiān', '休息时间');

-- Money & Banking (15 phrases)
insert into public.phrases (category, english, english_pronunciation, english_context, shona, shona_pronunciation, shona_context, ndebele, ndebele_pronunciation, ndebele_context, chinese, chinese_pronunciation, chinese_context) values
('money', 'How much?', 'how much', 'Price inquiry', 'Marii?', 'MAH-ree', 'Kubvunza mutengo', 'Malini?', 'mah-LEE-nee', 'Ukubuza intengo', '多少钱?', 'duō shao qián', '价格询问'),
('money', 'That''s expensive', 'thats ex-PEN-siv', 'Price comment', 'Zvinodhura', 'zvee-noh-DOO-rah', 'Kutaura pamusoro pemutengo', 'Kuyabiza', 'koo-yah-BEE-zah', 'Ukukhuluma ngentengo', '太贵了', 'tài guì le', '价格评论'),
('money', 'Do you accept cards?', 'doo yoo ak-SEPT kardz', 'Payment method', 'Munogamuchira makadhi here?', 'moo-noh-gah-moo-CHEE-rah mah-KAH-dee HEH-reh', 'Nzira yekubhadhara', 'Uyawamukela amakhadi yini?', 'oo-yah-wah-moo-KEH-lah ah-mah-KAH-dee YEE-nee', 'Indlela yokukhokha', '接受银行卡吗?', 'jiē shòu yín háng kǎ ma', '付款方式'),
('money', 'Where is the ATM?', 'wair iz thee AY-tee-em', 'Finding machine', 'ATM iripi?', 'AY-tee-em ee-REE-pee', 'Kutsvaga muchina', 'I-ATM ikuphi?', 'ee-AY-tee-em ee-KOO-pee', 'Ukufuna umshini', 'ATM在哪里?', 'ATM zài nǎ lǐ', '寻找机器'),
('money', 'I need to withdraw money', 'eye need too with-DRAW MUN-ee', 'Banking action', 'Ndinoda kutora mari', 'nn-dee-NOH-dah koo-TOH-rah MAH-ree', 'Chiito chebhangi', 'Ngidinga ukukhipha imali', 'ng-ee-DEEN-gah oo-koo-KEE-phah ee-MAH-lee', 'Isenzo sebhange', '我需要取钱', 'wǒ xū yào qǔ qián', '银行操作'),
('money', 'Can I pay later?', 'kan eye pay LAY-ter', 'Credit request', 'Ndingabhadhara gare gare here?', 'nn-deen-gah-bah-DAH-rah GAH-reh GAH-reh HEH-reh', 'Kukumbira chikwereti', 'Ngingakhokhela kamuva yini?', 'ng-een-gah-koh-KEH-lah kah-MOO-vah YEE-nee', 'Ukucela isikweletu', '能晚点付吗?', 'néng wǎn diǎn fù ma', '信用请求'),
('money', 'I don''t have money', 'eye dohnt hav MUN-ee', 'Financial situation', 'Handina mari', 'hahn-DEE-nah MAH-ree', 'Mamiriro emari', 'Anginamali', 'ah-ng-ee-nah-MAH-lee', 'Isimo semali', '我没有钱', 'wǒ méi yǒu qián', '财务状况'),
('money', 'Can you give me change?', 'kan yoo giv mee chaynj', 'Small denomination request', 'Mungandipa shanduko here?', 'moon-gahn-dee-pah shahn-DOO-koh HEH-reh', 'Kukumbira mari duku', 'Linganginika ushintsho yini?', 'lee-ngahn-gee-NEE-kah oo-SHEEN-tshoh YEE-nee', 'Ukucela imali encane', '能找零吗?', 'néng zhǎo líng ma', '零钱请求'),
('money', 'Keep the change', 'keep thuh chaynj', 'Tip gesture', 'Siyana nazvo', 'see-YAH-nah NAH-zvoh', 'Kuponesa', 'Gcinisipo', 'g-chee-NEE-see-poh', 'Ukushiya', '不用找了', 'bù yòng zhǎo le', '小费'),
('money', 'Where is the bank?', 'wair iz thuh bank', 'Finding location', 'Bhangi iripi?', 'BAHN-gee ee-REE-pee', 'Kutsvaga nzvimbo', 'Ibhange likuphi?', 'ee-BAHN-geh lee-KOO-pee', 'Ukufuna indawo', '银行在哪里?', 'yín háng zài nǎ lǐ', '寻找位置'),
('money', 'I want to open an account', 'eye want too OH-pen an uh-KOWNT', 'Banking service', 'Ndinoda kuvhura account', 'nn-dee-NOH-dah koo-VOO-rah ah-KOWNT', 'Sevhisi yebhangi', 'Ngifuna ukuvula i-akhawunti', 'ng-ee-FOO-nah oo-koo-VOO-lah ee-ah-KAW-ntee', 'Inkonzo yebhange', '我想开户', 'wǒ xiǎng kāi hù', '银行服务'),
('money', 'What''s the exchange rate?', 'whats thee ex-CHAYNJ rayt', 'Currency inquiry', 'Rate yekuchinjana ndeyei?', 'RAYT yeh-koo-cheen-JAH-nah nn-DEH-yay', 'Kubvunza nezvemari', 'Yimalini i-ekhishenji reyithi?', 'yee-mah-LEE-nee ee-eh-kee-SHEHN-jee RAY-tee', 'Ukubuza ngemali', '汇率是多少?', 'huì lǜ shì duō shao', '货币询问'),
('money', 'Can you lend me...?', 'kan yoo lend mee', 'Loan request', 'Mungandikweretesa...?', 'moon-gahn-dee-kweh-reh-TEH-sah', 'Kukumbira chikwereti', 'Lingangikweleta...?', 'lee-ngahn-gee-kweh-LEH-tah', 'Ukucela ukweboleka', '能借给我...吗?', 'néng jiè gěi wǒ... ma', '借贷请求'),
('money', 'I''ll pay you back', 'ile pay yoo bak', 'Promise to repay', 'Ndichakudzorera', 'nn-dee-chah-koo-dzoh-REH-rah', 'Vimbiso yekudzosera', 'Ngizakubuyisela', 'ng-ee-zah-koo-boo-yee-SEH-lah', 'Isithembiso sokubuyisela', '我会还你的', 'wǒ huì huán nǐ de', '承诺还款'),
('money', 'Split the bill', 'split thuh bil', 'Shared payment', 'Tigove bhiri', 'tee-GOH-veh BEE-ree', 'Kubhadhara pamwe chete', 'Siyahlukanise ibhili', 'see-yah-hloo-kah-NEE-seh ee-BEE-lee', 'Ukuhlukaniselana ukubhadala', '平摊账单', 'píng tān zhàng dān', '共同付款');

-- Weather & Time (15 phrases)
insert into public.phrases (category, english, english_pronunciation, english_context, shona, shona_pronunciation, shona_context, ndebele, ndebele_pronunciation, ndebele_context, chinese, chinese_pronunciation, chinese_context) values
('weather', 'It''s hot today', 'its hot tuh-DAY', 'Weather observation', 'Kunopisa nhasi', 'koo-noh-PEE-sah nn-HAH-see', 'Kutarisa mamiriro ekunze', 'Kuyashisa lamuhla', 'koo-yah-SHEE-sah lah-MOO-hlah', 'Ukubheka isimo sezulu', '今天很热', 'jīn tiān hěn rè', '天气观察'),
('weather', 'It''s cold', 'its kohld', 'Temperature', 'Kunotonhora', 'koo-noh-tohn-HOH-rah', 'Tembiricha', 'Kuyabanda', 'koo-yah-BAHN-dah', 'Izinga lokushisa', '很冷', 'hěn lěng', '温度'),
('weather', 'It''s raining', 'its RAYN-ing', 'Current weather', 'Kuri kunaya', 'KOO-ree koo-NAH-yah', 'Mamiriro ekunze azvino', 'Kuyanetha', 'koo-yah-NEH-tah', 'Isimo sezulu samanje', '下雨了', 'xià yǔ le', '当前天气'),
('weather', 'Will it rain?', 'wil it rayn', 'Weather forecast', 'Kunganaya here?', 'koo-ng-gah-NAH-yah HEH-reh', 'Kufungidzira mamiriro ekunze', 'Kunganetha yini?', 'koo-ng-gah-NEH-tah YEE-nee', 'Ukubikezela isimo sezulu', '会下雨吗?', 'huì xià yǔ ma', '天气预报'),
('weather', 'What time is it?', 'what time iz it', 'Time inquiry', 'Nguva yakadini?', 'nn-GOO-vah yah-kah-DEE-nee', 'Kubvunza nguva', 'Kusisikhathi sini?', 'koo-see-see-KAH-thee SEE-nee', 'Ukubuza isikhathi', '现在几点?', 'xiàn zài jǐ diǎn', '时间询问'),
('weather', 'It''s morning', 'its MOR-ning', 'Time of day', 'Mangwanani', 'mahn-gwah-NAH-nee', 'Nguva yezuva', 'Kusekuseni', 'koo-seh-koo-SEH-nee', 'Isikhathi sosuku', '早上', 'zǎo shàng', '一天的时间'),
('weather', 'It''s afternoon', 'its af-ter-NOON', 'Time of day', 'Masikati', 'mah-see-KAH-tee', 'Nguva yezuva', 'Emini', 'eh-MEE-nee', 'Isikhathi sosuku', '下午', 'xià wǔ', '一天的时间'),
('weather', 'It''s evening', 'its EEV-ning', 'Time of day', 'Manheru', 'mahn-HEH-roo', 'Nguva yezuva', 'Kusihlwa', 'koo-see-HLWAH', 'Isikhathi sosuku', '晚上', 'wǎn shàng', '一天的时间'),
('weather', 'It''s night', 'its nite', 'Time of day', 'Usiku', 'oo-SEE-koo', 'Nguva yezuva', 'Kubusuku', 'koo-boo-SOO-koo', 'Isikhathi sosuku', '晚上/夜里', 'wǎn shàng/yè lǐ', '一天的时间'),
('weather', 'What day is it?', 'what day iz it', 'Day inquiry', 'Izuva ripi?', 'ee-ZOO-vah REE-pee', 'Kubvunza zuva', 'Yiluphi usuku?', 'yee-LOO-pee oo-SOO-koo', 'Ukubuza usuku', '今天星期几?', 'jīn tiān xīng qī jǐ', '日期询问'),
('weather', 'It''s Monday', 'its MUN-day', 'Day of week', 'Muvhuro', 'moo-VOO-roh', 'Zuva revhiki', 'UMsombuluko', 'oo-m-sohm-boo-LOO-koh', 'Usuku lweviki', '星期一', 'xīng qī yī', '一周的某天'),
('weather', 'What''s the date?', 'whats thuh dayt', 'Calendar inquiry', 'Ndezuva ripi?', 'nn-deh-ZOO-vah REE-pee', 'Kubvunza kalenda', 'Ngoluphi usuku?', 'ng-oh-LOO-pee oo-SOO-koo', 'Ukubuza ikhalenda', '今天几号?', 'jīn tiān jǐ hào', '日历询问'),
('weather', 'It''s sunny', 'its SUN-ee', 'Weather condition', 'Zuva rinobuda', 'ZOO-vah ree-noh-BOO-dah', 'Mamiriro ekunze', 'Lilanga liyaphuma', 'lee-LAHN-gah lee-yah-PHOO-mah', 'Isimo sezulu', '晴天', 'qíng tiān', '天气状况'),
('weather', 'It''s windy', 'its WIN-dee', 'Weather condition', 'Mhepo inovhuvhuta', 'mm-HEH-poh ee-noh-voo-VOO-tah', 'Mamiriro ekunze', 'Kuyavutha', 'koo-yah-VOO-tah', 'Isimo sezulu', '有风', 'yǒu fēng', '天气状况'),
('weather', 'It''s cloudy', 'its KLOW-dee', 'Weather condition', 'Kumakore', 'koo-mah-KOH-reh', 'Mamiriro ekunze', 'Kunamafu', 'koo-nah-mah-FOO', 'Isimo sezulu', '多云', 'duō yún', '天气状况');

-- Emotions & Social (15 phrases)
insert into public.phrases (category, english, english_pronunciation, english_context, shona, shona_pronunciation, shona_context, ndebele, ndebele_pronunciation, ndebele_context, chinese, chinese_pronunciation, chinese_context) values
('emotions', 'I''m happy', 'ime HAP-ee', 'Positive feeling', 'Ndiri kufara', 'nn-DEE-ree koo-FAH-rah', 'Manzwiro akanaka', 'Ngiyajabula', 'ng-ee-yah-jah-BOO-lah', 'Imizwa emihle', '我很开心', 'wǒ hěn kāi xīn', '积极情绪'),
('emotions', 'I''m sad', 'ime sad', 'Negative feeling', 'Ndiri kushungurudzika', 'nn-DEE-ree koo-shoon-goo-roo-DZEE-kah', 'Manzwiro asina kunaka', 'Ngilusizi', 'ng-ee-loo-SEE-zee', 'Imizwa engemihle', '我很难过', 'wǒ hěn nán guò', '消极情绪'),
('emotions', 'I''m tired', 'ime ty-erd', 'Physical state', 'Ndaneta', 'nn-dah-NEH-tah', 'Mamiriro emuviri', 'Ngikhathele', 'ng-ee-kah-TEH-leh', 'Isimo somzimba', '我很累', 'wǒ hěn lèi', '身体状态'),
('emotions', 'I''m angry', 'ime ANG-gree', 'Strong emotion', 'Ndiri kutsamwa', 'nn-DEE-ree koo-TSAHM-wah', 'Manzwiro akasimba', 'Ngiyathukuthela', 'ng-ee-yah-too-koo-TEH-lah', 'Imizwa eqinile', '我很生气', 'wǒ hěn shēng qì', '强烈情绪'),
('emotions', 'I''m scared', 'ime skaird', 'Fear emotion', 'Ndiri kutya', 'nn-DEE-ree koo-TYAH', 'Manzwiro ekutya', 'Ngiyesaba', 'ng-ee-yeh-SAH-bah', 'Imizwa yokwesaba', '我害怕', 'wǒ hài pà', '恐惧情绪'),
('emotions', 'I''m excited', 'ime ex-SY-ted', 'Enthusiastic feeling', 'Ndiri kufara zvikuru', 'nn-DEE-ree koo-FAH-rah zvee-KOO-roo', 'Manzwiro ekufara', 'Ngiyathokoza', 'ng-ee-yah-toh-KOH-zah', 'Imizwa yokujabula', '我很兴奋', 'wǒ hěn xīng fèn', '兴奋情绪'),
('emotions', 'I''m worried', 'ime WUR-eed', 'Anxious feeling', 'Ndiri kunetseka', 'nn-DEE-ree koo-neh-TSEH-kah', 'Manzwiro ekunetseka', 'Ngiyakhathazeka', 'ng-ee-yah-kah-tah-ZEH-kah', 'Imizwa yokukhathazeka', '我很担心', 'wǒ hěn dān xīn', '焦虑情绪'),
('emotions', 'I love you', 'eye luv yoo', 'Affection', 'Ndinokuda', 'nn-dee-noh-KOO-dah', 'Rudo', 'Ngiyakuthanda', 'ng-ee-yah-koo-TAHN-dah', 'Uthando', '我爱你', 'wǒ ài nǐ', '爱意'),
('emotions', 'I miss you', 'eye mis yoo', 'Longing', 'Ndinokushuva', 'nn-dee-noh-koo-SHOO-vah', 'Kushuvira', 'Ngiyakukhumbula', 'ng-ee-yah-koo-koom-BOO-lah', 'Ukukhumbula', '我想你', 'wǒ xiǎng nǐ', '思念'),
('emotions', 'Congratulations!', 'kun-grat-yoo-LAY-shunz', 'Celebration', 'Makorokoto!', 'mah-koh-roh-KOH-toh', 'Kupemberera', 'Halala!', 'hah-LAH-lah', 'Ukugubha', '恭喜!', 'gōng xǐ', '庆祝'),
('emotions', 'Good luck', 'good luk', 'Well wishes', 'Rombo rakanaka', 'ROHM-boh rah-kah-NAH-kah', 'Kuda zvakanaka', 'Ngikufisela inhlanhla', 'ng-ee-koo-fee-SEH-lah een-HLAHN-hlah', 'Ukufisela okuhle', '祝你好运', 'zhù nǐ hǎo yùn', '祝福'),
('emotions', 'Don''t worry', 'dohnt WUR-ee', 'Reassurance', 'Usanetseke', 'oo-sah-neh-TSEH-keh', 'Kunyaradza', 'Ungakhathazeki', 'oo-ngah-kah-tah-ZEH-kee', 'Ukududuza', '别担心', 'bié dān xīn', '安慰'),
('emotions', 'It''s okay', 'its oh-KAY', 'Acceptance', 'Zvakanaka', 'zvah-kah-NAH-kah', 'Kubvuma', 'Kulungile', 'koo-loo-NGEE-leh', 'Ukwamukela', '没关系', 'méi guān xi', '接受'),
('emotions', 'I''m proud of you', 'ime prowd uv yoo', 'Pride', 'Ndinozvidza newe', 'nn-dee-noh-ZVEE-dzah NEH-weh', 'Kuzvikudza', 'Ngiyakuziqhenya ngawe', 'ng-ee-yah-koo-zee-QHEH-nyah ng-ah-weh', 'Ukuziqhenya', '我为你骄傲', 'wǒ wèi nǐ jiāo ào', '自豪'),
('emotions', 'Well done', 'wel dun', 'Praise', 'Waita mushe', 'WAI-tah MOO-sheh', 'Kurumbidza', 'Wenze kahle', 'WEHN-zeh KAH-leh', 'Ukudumisa', '做得好', 'zuò de hǎo', '赞扬');

-- Work & Business (15 phrases)  
insert into public.phrases (category, english, english_pronunciation, english_context, shona, shona_pronunciation, shona_context, ndebele, ndebele_pronunciation, ndebele_context, chinese, chinese_pronunciation, chinese_context) values
('work', 'Where do you work?', 'wair doo yoo wurk', 'Job inquiry', 'Unoshanda kupi?', 'oo-noh-SHAHN-dah KOO-pee', 'Kubvunza nebasa', 'Usebenza kuphi?', 'oo-seh-BEHN-zah KOO-pee', 'Ukubuza ngomsebenzi', '你在哪里工作?', 'nǐ zài nǎ lǐ gōng zuò', '工作询问'),
('work', 'I''m looking for a job', 'ime LOOK-ing for uh job', 'Job seeking', 'Ndiri kutsvaga basa', 'nn-DEE-ree koo-TSVAH-gah BAH-sah', 'Kutsvaga basa', 'Ngifuna umsebenzi', 'ng-ee-FOO-nah oom-seh-BEHN-zee', 'Ukufuna umsebenzi', '我在找工作', 'wǒ zài zhǎo gōng zuò', '求职'),
('work', 'What do you do?', 'what doo yoo doo', 'Occupation inquiry', 'Unoita basa rei?', 'oo-noh-EE-tah BAH-sah ray', 'Kubvunza nebasa', 'Wenzani?', 'wehn-ZAH-nee', 'Ukubuza ngomsebenzi', '你做什么工作?', 'nǐ zuò shén me gōng zuò', '职业询问'),
('work', 'I''m a farmer', 'ime uh FAR-mer', 'Occupation', 'Ndiri murimi', 'nn-DEE-ree moo-REE-mee', 'Basa', 'Ngingumlimi', 'ng-een-goom-LEE-mee', 'Umsebenzi', '我是农民', 'wǒ shì nóng mín', '职业'),
('work', 'I''m a nurse', 'ime uh nurs', 'Medical profession', 'Ndiri mukoti', 'nn-DEE-ree moo-KOH-tee', 'Basa rekurapa', 'Ngingunesi', 'ng-een-goo-NEH-see', 'Umsebenzi wezempilo', '我是护士', 'wǒ shì hù shi', '医疗职业'),
('work', 'I''m a driver', 'ime uh DRY-ver', 'Transportation work', 'Ndiri mutyairi', 'nn-DEE-ree moo-TYAI-ree', 'Basa remafambiro', 'Ngingumshayeli', 'ng-een-goom-shah-YEH-lee', 'Umsebenzi wezokuthutha', '我是司机', 'wǒ shì sī jī', '交通工作'),
('work', 'Can I have your card?', 'kan eye hav yor kard', 'Business networking', 'Ndingawana kadhi yenyu here?', 'nn-deen-gah-WAH-nah KAH-dee YEH-nyoo HEH-reh', 'Kusangana mubhizinesi', 'Ngingathola ikhadi lakho yini?', 'ng-een-gah-TOH-lah ee-KAH-dee LAH-koh YEE-nee', 'Ukuxhumana ebhizinisini', '能给我你的名片吗?', 'néng gěi wǒ nǐ de míng piàn ma', '商务社交'),
('work', 'Let''s meet tomorrow', 'lets meet tuh-MAR-oh', 'Appointment', 'Ngatingasangane mangwana', 'ng-gah-teen-gah-sahn-GAH-neh mahn-GWAH-nah', 'Musangano', 'Asihlangane kusasa', 'ah-see-hlahn-GAH-neh koo-SAH-sah', 'Ukuhlangana', '我们明天见面吧', 'wǒ men míng tiān jiàn miàn ba', '约会'),
('work', 'I''ll call you', 'ile kawl yoo', 'Communication promise', 'Ndichakufonerai', 'nn-dee-chah-koo-foh-NEH-rye', 'Vimbiso yekutaurirana', 'Ngizakukufonela', 'ng-ee-zah-koo-koo-foh-NEH-lah', 'Isithembiso sokukhulumisana', '我会打电话给你', 'wǒ huì dǎ diàn huà gěi nǐ', '沟通承诺'),
('work', 'Send me an email', 'send mee an EE-mayl', 'Digital communication', 'Nditumire email', 'nn-dee-too-MEE-reh EE-mayl', 'Kutaurirana necomputer', 'Ngithumelele i-imeyli', 'ng-ee-too-meh-LEH-leh ee-ee-MAY-lee', 'Ukuxhumana ngekhompyutha', '给我发邮件', 'gěi wǒ fā yóu jiàn', '数字通讯'),
('work', 'What''s your number?', 'whats yor NUM-ber', 'Contact request', 'Nhamba yako ndeyei?', 'nn-HAHM-bah YAH-koh nn-DEH-yay', 'Kukumbira nhamba', 'Yiyiphi inombolo yakho?', 'yee-YEE-pee een-ohm-BOH-loh YAH-koh', 'Ukucela inombolo', '你的号码是多少?', 'nǐ de hào mǎ shì duō shao', '联系请求'),
('work', 'I''m busy', 'ime BIZ-ee', 'Unavailable', 'Ndiri kubatikana', 'nn-DEE-ree koo-bah-tee-KAH-nah', 'Kushaikwa', 'Ngimatasatasa', 'ng-ee-mah-tah-sah-TAH-sah', 'Ukungabi khona', '我很忙', 'wǒ hěn máng', '不可用'),
('work', 'I have a meeting', 'eye hav uh MEET-ing', 'Scheduled event', 'Ndine musangano', 'nn-DEE-neh moo-sahn-GAH-noh', 'Chiitiko chakarongwa', 'Nginomhlangano', 'ng-ee-nohm-hlahn-GAH-noh', 'Umcimbi ocwengiweyo', '我有个会议', 'wǒ yǒu ge huì yì', '预定事项'),
('work', 'When can we start?', 'when kan wee start', 'Project timing', 'Tingatanga rini?', 'teen-gah-TAHN-gah REE-nee', 'Nguva yepurojekiti', 'Singaqala nini?', 'seen-gah-QAH-lah NEE-nee', 'Isikhathi sephrojekthi', '我们什么时候开始?', 'wǒ men shén me shí hou kāi shǐ', '项目时间'),
('work', 'How much do you charge?', 'how much doo yoo charj', 'Service cost', 'Munobhadharisa marii?', 'moo-noh-bah-dah-REE-sah MAH-ree', 'Mutengo wesevhisi', 'Utshaja malini?', 'oo-TSHAH-jah mah-LEE-nee', 'Intengo yenkonzo', '你收费多少?', 'nǐ shōu fèi duō shao', '服务费用');
